import localFont from "next/font/local";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import SmoothContainer from "@/components/global/SmoothContainer";
import Cursor from "@/components/global/Cursor";
import Footer from "@/components/footer/Footer";
import FooterMobile from "@/components/footer/FooterMobile";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={playfair.style} className="bg-mwhite ">
        <SmoothContainer>
        <Navbar />

        {children}
        
        <FooterMobile/>
        <Footer/>
        </SmoothContainer>
        <Cursor/>
      </body>
    </html>
  );
}
